select * from `owid-covid-data2` order by `location`, `date`;CREATE TABLE `OWID_Daily` (
  `iso_code` text,
  `continent` text,
  `location` text,
  `date` text,
  `total_cases` int DEFAULT NULL,
  `new_cases` int DEFAULT NULL,
  `new_cases_smoothed` double DEFAULT NULL,
  `total_deaths` int DEFAULT NULL,
  `new_deaths` int DEFAULT NULL,
  `new_deaths_smoothed` double DEFAULT NULL,
  `total_cases_per_million` double DEFAULT NULL,
  `new_cases_per_million` double DEFAULT NULL,
  `new_cases_smoothed_per_million` double DEFAULT NULL,
  `total_deaths_per_million` double DEFAULT NULL,
  `new_deaths_per_million` double DEFAULT NULL,
  `new_deaths_smoothed_per_million` double DEFAULT NULL,
  `reproduction_rate` double DEFAULT NULL,
  `icu_patients` int DEFAULT NULL,
  `icu_patients_per_million` double DEFAULT NULL,
  `hosp_patients` int DEFAULT NULL,
  `hosp_patients_per_million` double DEFAULT NULL,
  `weekly_icu_admissions` int DEFAULT NULL,
  `weekly_icu_admissions_per_million` double DEFAULT NULL,
  `weekly_hosp_admissions` int DEFAULT NULL,
  `weekly_hosp_admissions_per_million` double DEFAULT NULL,
  `new_tests` int DEFAULT NULL,
  `total_tests` int DEFAULT NULL,
  `total_tests_per_thousand` double DEFAULT NULL,
  `new_tests_per_thousand` double DEFAULT NULL,
  `new_tests_smoothed` int DEFAULT NULL,
  `new_tests_smoothed_per_thousand` double DEFAULT NULL,
  `positive_rate` double DEFAULT NULL,
  `tests_per_case` double DEFAULT NULL,
  `tests_units` text,
  `total_vaccinations` int DEFAULT NULL,
  `people_vaccinated` int DEFAULT NULL,
  `people_fully_vaccinated` int DEFAULT NULL,
  `new_vaccinations` int DEFAULT NULL,
  `new_vaccinations_smoothed` int DEFAULT NULL,
  `total_vaccinations_per_hundred` double DEFAULT NULL,
  `people_vaccinated_per_hundred` double DEFAULT NULL,
  `people_fully_vaccinated_per_hundred` double DEFAULT NULL,
  `new_vaccinations_smoothed_per_million` int DEFAULT NULL,
  `stringency_index` double DEFAULT NULL,
  `population` int DEFAULT NULL,
  `population_density` double DEFAULT NULL,
  `median_age` double DEFAULT NULL,
  `aged_65_older` double DEFAULT NULL,
  `aged_70_older` double DEFAULT NULL,
  `gdp_per_capita` double DEFAULT NULL,
  `extreme_poverty` double DEFAULT NULL,
  `cardiovasc_death_rate` double DEFAULT NULL,
  `diabetes_prevalence` double DEFAULT NULL,
  `female_smokers` int DEFAULT NULL,
  `male_smokers` double DEFAULT NULL,
  `handwashing_facilities` double DEFAULT NULL,
  `hospital_beds_per_thousand` double DEFAULT NULL,
  `life_expectancy` double DEFAULT NULL,
  `human_development_index` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
